AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Service Catalog actions provider
Resources:
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      CodeUri: sc-actions-provider/
      Handler: app.lambda_handler
      Role: !GetAtt FunctionRole.Arn
      Timeout: 30
  AssociateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      CodeUri: sc-actions-provider/
      Handler: associate.lambda_handler
      Role: !GetAtt FunctionRole.Arn
      Timeout: 30
  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/AWSServiceCatalogAdminFullAccess"
        - "arn:aws:iam::aws:policy/AmazonSSMFullAccess"
        - "arn:aws:iam::aws:policy/IAMFullAccess"
Outputs:
  CreateFunctionArn:
    Value: !GetAtt CreateFunction.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-CreateFunctionArn'
  AssociateFunctionArn:
    Value: !GetAtt AssociateFunction.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-AssociateFunctionArn'
